apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      containers:
      - name: db-migration
        image: brendofut/fake-shop:v2
        command: ["flask", "db", "upgrade"]
        env:
        - name: DB_HOST
          value: postgre
        - name: DB_USER
          value: fakeshop
        - name: DB_PASSWORD
          value: Pg1234
        - name: DB_NAME
          value: fakeshop
        - name: FLASK_APP
          value: index.py
      restartPolicy: Never
  backoffLimit: 4
